/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChannelLight { 'status' : string, 'channel' : string }
export interface CommanderEvent {
  'id' : bigint,
  'action' : string,
  'feature' : string,
  'value' : string,
  'signalState' : string,
  'previousValue' : string,
  'timestamp' : bigint,
  'channel' : string,
  'autoFixed' : boolean,
  'eventType' : string,
}
export interface CommanderSlot {
  'lastWrite' : bigint,
  'value' : number,
  'slotId' : string,
  'featureName' : string,
}
export interface DiagnosticReport {
  'id' : bigint,
  'problemsFound' : Array<string>,
  'fixesApplied' : Array<string>,
  'timestamp' : bigint,
  'overallHealth' : string,
  'channelStatuses' : Array<[string, string]>,
}
export interface FullDiagnosticReport {
  'nodeStatus' : Array<[string, string]>,
  'powerChainStatus' : string,
  'totalSlotsUsed' : bigint,
  'timestamp' : bigint,
  'audioContextState' : string,
  'lastSaveTimestamp' : bigint,
  'channelLights' : Array<ChannelLight>,
}
export interface _SERVICE {
  /**
   * / Clears all Commander memory slots (clean cache).
   */
  'clearCommanderMemory' : ActorMethod<[], undefined>,
  /**
   * / Clears all event history (does not affect diagnostic reports or slots).
   */
  'clearHistory' : ActorMethod<[], undefined>,
  /**
   * / Returns all unresolved error events (eventType == "error" and not autoFixed).
   */
  'getActiveProblems' : ActorMethod<[], Array<CommanderEvent>>,
  /**
   * / Returns all stored Commander slots (up to 3,000), unordered.
   */
  'getCommanderState' : ActorMethod<[], Array<CommanderSlot>>,
  /**
   * / Returns the most recent diagnostic reports, newest first.
   */
  'getDiagnosticReports' : ActorMethod<[bigint], Array<DiagnosticReport>>,
  /**
   * / Returns a full diagnostic snapshot of the Commander chip and power chain.
   */
  'getFullDiagnosticReport' : ActorMethod<[], FullDiagnosticReport>,
  /**
   * / Returns paginated history, newest first.
   * / offset=0 means start from the most recent event.
   */
  'getHistory' : ActorMethod<[bigint, bigint], Array<CommanderEvent>>,
  /**
   * / Returns the most recent events for a specific channel, newest first.
   */
  'getHistoryByChannel' : ActorMethod<[string, bigint], Array<CommanderEvent>>,
  /**
   * / Returns the most recent events for a specific feature, newest first.
   */
  'getHistoryByFeature' : ActorMethod<[string, bigint], Array<CommanderEvent>>,
  /**
   * / Returns the single most recent diagnostic report.
   */
  'getLatestDiagnosticReport' : ActorMethod<[], [] | [DiagnosticReport]>,
  'getStats' : ActorMethod<
    [],
    {
      'channelHealth' : Array<[string, string]>,
      'totalEvents' : bigint,
      'lastScanTimestamp' : bigint,
      'activeProblems' : bigint,
    }
  >,
  /**
   * / Logs a full diagnostic report and returns its ID.
   */
  'logDiagnosticReport' : ActorMethod<
    [Array<[string, string]>, Array<string>, Array<string>, string],
    bigint
  >,
  /**
   * / Log a Commander event. Returns the new event's ID.
   * / When the 1001st event is added the oldest is automatically dropped.
   */
  'logEvent' : ActorMethod<
    [string, string, string, string, string, string, string, boolean],
    bigint
  >,
  /**
   * / Save (or update) a Commander memory slot.
   * / When the 3,001st unique slot is written the oldest slot is evicted.
   */
  'recordEvent' : ActorMethod<[string, string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];