/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CommanderEvent = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'feature' : IDL.Text,
  'value' : IDL.Text,
  'signalState' : IDL.Text,
  'previousValue' : IDL.Text,
  'timestamp' : IDL.Int,
  'channel' : IDL.Text,
  'autoFixed' : IDL.Bool,
  'eventType' : IDL.Text,
});
export const CommanderSlot = IDL.Record({
  'lastWrite' : IDL.Int,
  'value' : IDL.Float64,
  'slotId' : IDL.Text,
  'featureName' : IDL.Text,
});
export const DiagnosticReport = IDL.Record({
  'id' : IDL.Nat,
  'problemsFound' : IDL.Vec(IDL.Text),
  'fixesApplied' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
  'overallHealth' : IDL.Text,
  'channelStatuses' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ChannelLight = IDL.Record({
  'status' : IDL.Text,
  'channel' : IDL.Text,
});
export const FullDiagnosticReport = IDL.Record({
  'nodeStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'powerChainStatus' : IDL.Text,
  'totalSlotsUsed' : IDL.Nat,
  'timestamp' : IDL.Int,
  'audioContextState' : IDL.Text,
  'lastSaveTimestamp' : IDL.Int,
  'channelLights' : IDL.Vec(ChannelLight),
});

export const idlService = IDL.Service({
  'clearCommanderMemory' : IDL.Func([], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'getActiveProblems' : IDL.Func([], [IDL.Vec(CommanderEvent)], ['query']),
  'getCommanderState' : IDL.Func([], [IDL.Vec(CommanderSlot)], ['query']),
  'getDiagnosticReports' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DiagnosticReport)],
      ['query'],
    ),
  'getFullDiagnosticReport' : IDL.Func([], [FullDiagnosticReport], ['query']),
  'getHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CommanderEvent)],
      ['query'],
    ),
  'getHistoryByChannel' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(CommanderEvent)],
      ['query'],
    ),
  'getHistoryByFeature' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(CommanderEvent)],
      ['query'],
    ),
  'getLatestDiagnosticReport' : IDL.Func(
      [],
      [IDL.Opt(DiagnosticReport)],
      ['query'],
    ),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'channelHealth' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          'totalEvents' : IDL.Nat,
          'lastScanTimestamp' : IDL.Int,
          'activeProblems' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'logDiagnosticReport' : IDL.Func(
      [
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'logEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'recordEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CommanderEvent = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'feature' : IDL.Text,
    'value' : IDL.Text,
    'signalState' : IDL.Text,
    'previousValue' : IDL.Text,
    'timestamp' : IDL.Int,
    'channel' : IDL.Text,
    'autoFixed' : IDL.Bool,
    'eventType' : IDL.Text,
  });
  const CommanderSlot = IDL.Record({
    'lastWrite' : IDL.Int,
    'value' : IDL.Float64,
    'slotId' : IDL.Text,
    'featureName' : IDL.Text,
  });
  const DiagnosticReport = IDL.Record({
    'id' : IDL.Nat,
    'problemsFound' : IDL.Vec(IDL.Text),
    'fixesApplied' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
    'overallHealth' : IDL.Text,
    'channelStatuses' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ChannelLight = IDL.Record({
    'status' : IDL.Text,
    'channel' : IDL.Text,
  });
  const FullDiagnosticReport = IDL.Record({
    'nodeStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'powerChainStatus' : IDL.Text,
    'totalSlotsUsed' : IDL.Nat,
    'timestamp' : IDL.Int,
    'audioContextState' : IDL.Text,
    'lastSaveTimestamp' : IDL.Int,
    'channelLights' : IDL.Vec(ChannelLight),
  });
  
  return IDL.Service({
    'clearCommanderMemory' : IDL.Func([], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'getActiveProblems' : IDL.Func([], [IDL.Vec(CommanderEvent)], ['query']),
    'getCommanderState' : IDL.Func([], [IDL.Vec(CommanderSlot)], ['query']),
    'getDiagnosticReports' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DiagnosticReport)],
        ['query'],
      ),
    'getFullDiagnosticReport' : IDL.Func([], [FullDiagnosticReport], ['query']),
    'getHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CommanderEvent)],
        ['query'],
      ),
    'getHistoryByChannel' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(CommanderEvent)],
        ['query'],
      ),
    'getHistoryByFeature' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(CommanderEvent)],
        ['query'],
      ),
    'getLatestDiagnosticReport' : IDL.Func(
        [],
        [IDL.Opt(DiagnosticReport)],
        ['query'],
      ),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'channelHealth' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
            'totalEvents' : IDL.Nat,
            'lastScanTimestamp' : IDL.Int,
            'activeProblems' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'logDiagnosticReport' : IDL.Func(
        [
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'logEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'recordEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };