/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChannelLight {
    status: string;
    channel: string;
}
export interface FullDiagnosticReport {
    nodeStatus: Array<[string, string]>;
    powerChainStatus: string;
    totalSlotsUsed: bigint;
    timestamp: bigint;
    audioContextState: string;
    lastSaveTimestamp: bigint;
    channelLights: Array<ChannelLight>;
}
export interface DiagnosticReport {
    id: bigint;
    problemsFound: Array<string>;
    fixesApplied: Array<string>;
    timestamp: bigint;
    overallHealth: string;
    channelStatuses: Array<[string, string]>;
}
export interface CommanderEvent {
    id: bigint;
    action: string;
    feature: string;
    value: string;
    signalState: string;
    previousValue: string;
    timestamp: bigint;
    channel: string;
    autoFixed: boolean;
    eventType: string;
}
export interface CommanderSlot {
    lastWrite: bigint;
    value: number;
    slotId: string;
    featureName: string;
}
export interface backendInterface {
    /**
     * / Clears all Commander memory slots (clean cache).
     */
    clearCommanderMemory(): Promise<void>;
    /**
     * / Clears all event history (does not affect diagnostic reports or slots).
     */
    clearHistory(): Promise<void>;
    /**
     * / Returns all unresolved error events (eventType == "error" and not autoFixed).
     */
    getActiveProblems(): Promise<Array<CommanderEvent>>;
    /**
     * / Returns all stored Commander slots (up to 3,000), unordered.
     */
    getCommanderState(): Promise<Array<CommanderSlot>>;
    /**
     * / Returns the most recent diagnostic reports, newest first.
     */
    getDiagnosticReports(limit: bigint): Promise<Array<DiagnosticReport>>;
    /**
     * / Returns a full diagnostic snapshot of the Commander chip and power chain.
     */
    getFullDiagnosticReport(): Promise<FullDiagnosticReport>;
    /**
     * / Returns paginated history, newest first.
     * / offset=0 means start from the most recent event.
     */
    getHistory(limit: bigint, offset: bigint): Promise<Array<CommanderEvent>>;
    /**
     * / Returns the most recent events for a specific channel, newest first.
     */
    getHistoryByChannel(channel: string, limit: bigint): Promise<Array<CommanderEvent>>;
    /**
     * / Returns the most recent events for a specific feature, newest first.
     */
    getHistoryByFeature(feature: string, limit: bigint): Promise<Array<CommanderEvent>>;
    /**
     * / Returns the single most recent diagnostic report.
     */
    getLatestDiagnosticReport(): Promise<DiagnosticReport | null>;
    getStats(): Promise<{
        channelHealth: Array<[string, string]>;
        totalEvents: bigint;
        lastScanTimestamp: bigint;
        activeProblems: bigint;
    }>;
    /**
     * / Logs a full diagnostic report and returns its ID.
     */
    logDiagnosticReport(channelStatuses: Array<[string, string]>, problemsFound: Array<string>, fixesApplied: Array<string>, overallHealth: string): Promise<bigint>;
    /**
     * / Log a Commander event. Returns the new event's ID.
     * / When the 1001st event is added the oldest is automatically dropped.
     */
    logEvent(eventType: string, feature: string, channel: string, action: string, value: string, previousValue: string, signalState: string, autoFixed: boolean): Promise<bigint>;
    /**
     * / Save (or update) a Commander memory slot.
     * / When the 3,001st unique slot is written the oldest slot is evicted.
     */
    recordEvent(slotId: string, featureName: string, value: number): Promise<void>;
}
import type { DiagnosticReport as _DiagnosticReport } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearCommanderMemory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCommanderMemory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCommanderMemory();
            return result;
        }
    }
    async clearHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHistory();
            return result;
        }
    }
    async getActiveProblems(): Promise<Array<CommanderEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProblems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProblems();
            return result;
        }
    }
    async getCommanderState(): Promise<Array<CommanderSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommanderState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommanderState();
            return result;
        }
    }
    async getDiagnosticReports(arg0: bigint): Promise<Array<DiagnosticReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiagnosticReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiagnosticReports(arg0);
            return result;
        }
    }
    async getFullDiagnosticReport(): Promise<FullDiagnosticReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullDiagnosticReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullDiagnosticReport();
            return result;
        }
    }
    async getHistory(arg0: bigint, arg1: bigint): Promise<Array<CommanderEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory(arg0, arg1);
            return result;
        }
    }
    async getHistoryByChannel(arg0: string, arg1: bigint): Promise<Array<CommanderEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryByChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryByChannel(arg0, arg1);
            return result;
        }
    }
    async getHistoryByFeature(arg0: string, arg1: bigint): Promise<Array<CommanderEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryByFeature(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryByFeature(arg0, arg1);
            return result;
        }
    }
    async getLatestDiagnosticReport(): Promise<DiagnosticReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestDiagnosticReport();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestDiagnosticReport();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<{
        channelHealth: Array<[string, string]>;
        totalEvents: bigint;
        lastScanTimestamp: bigint;
        activeProblems: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async logDiagnosticReport(arg0: Array<[string, string]>, arg1: Array<string>, arg2: Array<string>, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logDiagnosticReport(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDiagnosticReport(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async logEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async recordEvent(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordEvent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordEvent(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiagnosticReport]): DiagnosticReport | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
